language: java
sudo: enabled
jdk:
  - oraclejdk8
before_install:
- sudo add-apt-repository http://archive.ubuntu.com/ubuntu/ -y
- sudo apt-get update -y
script:
- ant build
- ant 'AllTestSuite'
